const instructions = {
    MOV_LIT_RD:         0x10,
    MOV_RS_RD:          0x11,
    STR_RS_MEM:         0x12,
    LDR_MEM_RD:         0x13,
    STR_LIT_MEM:        0x1B,
    STR_REG_IND_REG:    0x1C,
    STR_LIT_OFF_REG:    0x1D,
    
    ADD_RX_RY:          0x14,
    ADD_LIT_REG:        0x3F,
    SUB_LIT_REG:        0x16,
    SUB_REG_LIT:        0x1E,
    SUB_RX_RY:          0x1F,
    INC_REG:            0x35,
    DEC_REG:            0x36,
    MUL_LIT_REG:        0x20,
    MUL_REG_REG:        0x21,

    LSL_REG_LIT:        0x26,
    LSL_REG_REG:        0x27,
    LSR_REG_LIT:        0x2A,
    LSR_REG_REG:        0x2B,
    AND_REG_LIT:        0x2E,   
    AND_REG_REG:        0x2F,
    OR_REG_LIT:         0x30,
    OR_REG_REG:         0x31,
    XOR_REG_LIT:        0x32,
    XOR_REG_REG:        0x33,
    NOT:                0x34,   

    JMP_NOT_EQ:         0x15,
    JNE_REG:            0x40,
    JEQ_REG:            0x3E,
    JEQ_LIT:            0x41,
    JLT_REG:            0x42,   
    JLT_LIT:            0x43,
    JGT_REG:            0x44,
    JGT_LIT:            0x45,
    JLE_REG:            0x46,
    JLE_LIT:            0x47,
    JGE_REG:            0x48,
    JGE_LIT:            0x49,

    PSH_LIT:            0x17,
    PSH_RS:             0x18,
    POP:                0x1A,
    CAL_LIT:            0x5E,
    CAL_RS:             0x5F,
    RET:                0x60,
    HLT:                0xFF
}

export default instructions;
